![](../assets/header_image.png)

# Optional Assignment: Python, NumPy and Vectorization
This assignment gives you a brief introduction to some of the scientific computing used in this course. We will use the popular NumPy library that is used for many scientific computing applications.


In this optional assignment, you will learn about NumPy and more Python skills that are recommended to know for the upcoming assigments. This notebook is recommended to students who do not have any expierence in NumPy. You will learn about

- Vectors
- Matrices
- Operations on Matrices
- Operations on Vectors
- Indexing
- Accessing Elements

Let's start by importing numpy. Execute the cell below

In [21]:
import numpy as np
import time

You can see that we imported Numpy as `np`. This is the abbreviation for `numpy` and we can now access all numpy functions with `np`:

In [22]:
np.sum([1, 2, 3])

6

## References
We can provide here only a limited introduction to NumPy, because this library is quite huge and has many features. Check out the links below if you want to learn more about this library:
- NumPy Documentation: [NumPy.org](https://NumPy.org/doc/stable/)

## Python and NumPy
Python is one of the the programming languages that we will use in this MOOC. It has become very popular among data scientists and machine learning engineers, because it supports many different libraries and tools such as Jupter Notebooks. Furthermore, the syntax is quite easy to understand, but supports full object oriented programming, aswell as basic mathematical operations. NumPy is a Python library which gives Python the fundamental power for scientific computing. It adds a support for more numeric data types, vectors, matrices and matrix operations. Additionally, the core of NumPy is based on a well-optimized C code which enables, fast and efficient computations.

### Vectors, Matrices and Tensors
Before we are getting into details lets start by recapping the names for basic mathematical objects.

- **Vector** is an array with a single dimension (there’s no difference between row and column vectors)
- **Matrix** refers to an array with two dimensions
- **Tensor** for 3-D or higher dimensional arrays, the term *tensor* is also commonly used

# Vectors
A vector $x$ is an ordered array of numbers, where all elements have the same data type. The "length" of a vector is usually denoted by mathematicians as a *rank* and corresponds to $\text{rank}(x) = n$ for the example below. Using Python and NumPy we often denote the length along a *dimension*. Each element in the array can be accessed with an index. In linear algebra, the elements of a vector are often indexed from $1$ to $n$, where $i=1$ denotes the first element $x_1$ and $n$ the last element $x_n$. In programming languages however, one usually start counting from 0. Hence, the $0^{th}$ element $x_0$ is the first element in the array and $x_{n-1}$ is the last element.
 
NumPy and Python and also other programming languages:
$$
x =
\begin{pmatrix} 
x_{0}  \\
x_{1}  \\
...        \\
x_{n-1} \\
\end{pmatrix}
$$


Typical mathematical notation:

$$
x =
\begin{pmatrix} 
x_{1}  \\
x_{2}  \\
...        \\
x_{n} \\
\end{pmatrix}
$$

## NumPy Arrays

NumPy's basic data structure is an indexable, n-dimensional *array* containing elements of the same type (`dtype`). Right away, you may notice we have overloaded the term 'dimension'. Above, it was the number of elements in the vector, here, dimension refers to the number of indexes of an array. A one-dimensional or 1-D array has one index.

 - 1-D array, shape (n,): n elements indexed [0] through [n-1]
 

## Vector Creation


Data creation functions in NumPy will generally have a first parameter which is the shape of the object. This can either be a single value for a 1-D result or a tuple (n,m,...) specifying the shape of the result. Below are examples of creating vectors using these functions.

In [101]:
a = np.zeros(4)
print(f"a = np.zeros(4)\na = {a}\na shape = {a.shape}\na data type = {a.dtype}")
print("\n")

a = np.zeros((4,))
print(f"a = np.zeros((4,))\na = {a}\na shape = {a.shape}\na data type = {a.dtype}")
print("\n")

a = np.ones((4, 4))
print(f"a = np.ones((4, 4))\na = \n{a}\na shape = {a.shape}\na data type = {a.dtype}")
print("\n")

a = np.random.random_sample(4)
print(f"a = np.random.random_sample(4)\na = {a}\na shape = {a.shape}\na data type = {a.dtype}")
print("\n")

a = np.random.rand(4)
print(f"a = np.random.rand(4): \na = {a}, \na shape = {a.shape}, \na data type = {a.dtype}")

a = np.zeros(4)
a = [0. 0. 0. 0.]
a shape = (4,)
a data type = float64


a = np.zeros((4,))
a = [0. 0. 0. 0.]
a shape = (4,)
a data type = float64


a = np.ones((4, 4))
a = 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
a shape = (4, 4)
a data type = float64


a = np.random.random_sample(4)
a = [0.66123976 0.30659156 0.3543123  0.07109989]
a shape = (4,)
a data type = float64


a = np.random.rand(4): 
a = [0.41111495 0.45754396 0.07473088 0.9940063 ], 
a shape = (4,), 
a data type = float64


### We can also create sequences:

In [24]:
a = np.arange(4.)
print(f"a = np.arange(4.):     \na = {a}, \na shape = {a.shape}, \na data type = {a.dtype}")

a = np.arange(4.):     
a = [0. 1. 2. 3.], 
a shape = (4,), 
a data type = float64


### We can also instert custom values:

In [25]:
a = np.array([5,4,3,2])
print(f"a = np.array([5,4,3,2]):  \na = {a},     \na shape = {a.shape}, \na data type = {a.dtype}")
print("\n")

a = np.array([5.,4,3,2])
print(f"a = np.array([5.,4,3,2]):\na = {a}, \na shape = {a.shape}, \na data type = {a.dtype}")

a = np.array([5,4,3,2]):  
a = [5 4 3 2],     
a shape = (4,), 
a data type = int64


a = np.array([5.,4,3,2]):
a = [5. 4. 3. 2.], 
a shape = (4,), 
a data type = float64


These have all created a one-dimensional vector  `a` with four elements. `a.shape` returns the dimensions. Here we see a.shape = `(4,)` indicating a 1-d array with 4 elements.  

## Operations on Vectors

### Vector Indexing
Elements of vectors can be accessed via indexing and slicing. NumPy provides a very complete set of indexing and slicing capabilities. We can cover only a small part of the syntax in this tutorial. If you want to get an in-depth knowledge please read the official documentation about [Slicing and Indexing](https://NumPy.org/doc/stable/reference/arrays.indexing.html). Now, we want to clarify the difference between *indexing* and *slicing*

* **Indexing** means referring to *an element* of an array by its position within the array.  
* **Slicing** means getting a *subset* of elements from an array based on their indices.

NumPy starts indexing at zero so the 3rd element of an vector $a$ is `a[2]`.

In [26]:
#vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

#access an element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


### Vector Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

In [27]:
a = np.arange(10)
print(f"a        =  {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a        =  [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


<a name="toc_40015_3.4.3"></a>
### 3.4.3 Single vector operations
There are a number of useful operations that involve operations on a single vector.

In [28]:
a = np.array([1,2,3,4])
print(f"a             : {a}")

# negate elements of a
b = -a 
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


<a name="toc_40015_3.4.4"></a>
### 3.4.4 Vector Vector element-wise operations
Most of the NumPy arithmetic, logical and comparison operations apply to vectors as well. These operators work on an element-by-element basis. For example 
$$ c_i = a_i + b_i $$

In [30]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a - b}")

Binary operators work element wise: [2 4 0 0]


Of course, for this to work correctly, the vectors must be of the same size:

In [32]:
#try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


<a name="toc_40015_3.4.5"></a>
### 3.4.5 Scalar Vector operations
Vectors can be 'scaled' by scalar values. A scalar value is just a number. The scalar multiplies all the elements of the vector.

In [34]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


### Vectorization: Vector Vector dot product
We want to test the effectiveness of vectorization by implementing a vector dot product between two arrays $a$ and $b$:

$$
a \cdot b = \sum^{n-1}_{i=0} a_i b_i
$$

We will implement the function in two ways:

* **Explicit Loop**: Iterate over all elements of the vectors and use indexing to retrieve the elements, then perform multiplication and addition.
* **NumPy**: Use numpy's build-in functions `np.dot`

Vector dot product requires the dimensions of the two vectors to be the same. 

Let's implement our own version of the dot product below:

**Using a for loop**, implement a function which returns the dot product of two vectors. The function to return given inputs $a$ and $b$:
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
Assume both `a` and `b` are the same shape.

In [37]:
def dot_vectorized(a, b):
    """
    Compute the dot product of two vectors
    Arguments:
        a: numpy nd array with length n
        b: numpy nd array with length n
    Returns:
        x: dot product of a and b as scalar
    """
    return np.sum(a*b)

In [36]:
def dot_loop(a, b): 
    """
    Compute the dot product of two vectors
    Arguments:
        a: numpy nd array with length n
        b: numpy nd array with length n
    Returns:
        x: dot product of a and b as scalar
    """
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

You can see that the implementation in `dot_loop()` matches the results of `dot_vectorized()` and `np.dot()`

In [38]:
a = np.array([5, 3, 2, 1])
b = np.array([-1, 9, 7, 2])
print(f"Function: dot_loop(a, b) \t = {dot_loop(a, b)}")

# Function dot_vectorized
c = dot_vectorized(a, b)
print(f"Function: dot_vectorized(a, b) \t = {dot_loop(a, b)}")

# Build in numpy's dot function
c = np.dot(a, b)
print(f"NumPy Build-In: np.dot(a, b) \t = {c}") 

Function: dot_loop(a, b) 	 = 38
Function: dot_vectorized(a, b) 	 = 38
NumPy Build-In: np.dot(a, b) 	 = 38


In [ ]:
dd



Now, let's measure the **time** that each function needs to compute for two very large vectors.

<a name="toc_40015_3.4.7"></a>
### 3.4.7 The Need for Speed: vector vs for loop
We utilized the NumPy  library because it improves speed memory efficiency. Let's demonstrate:

In [53]:
np.random.seed(1337)
a = np.random.rand(10000000) 
b = np.random.rand(10000000)


tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time
print(f"np.dot(a, b) =\t\t\t {c:.4f}")
print(f"Build-In Function: \t\t {1000*(toc-tic):.4f} ms ")
print("\n")



tic = time.time()  # capture start time
c = dot_vectorized(a, b)
toc = time.time()  # capture end time
print(f"dot_vectorized(a, b) =\t\t {c:.4f}")
print(f"Function dot_vectorized(a, b): \t {1000*(toc-tic):.4f} ms ")
print("\n")



tic = time.time()  # capture start time
c = dot_loop(a,b)
toc = time.time()  # capture end time
print(f"dot_loop(a, b) =\t\t {c:.4f}")
print(f"Function dot_loop(a, b): \t {1000*(toc-tic):.4f} ms ")


del(a);del(b)  # remove arrays from memory

np.dot(a, b) =			 2499424.8578
Build-In Function: 		 5.1975 ms 


dot_vectorized(a, b) =		 2499424.8578
Function dot_vectorized(a, b): 	 18.0113 ms 


dot_loop(a, b) =		 2499424.8578
Function dot_loop(a, b): 	 1740.0916 ms 


As you can see, the build-in vectorized implementation gives a much better performance than manual loos. This is because NumPy makes better use of available data parallelism in the underlying hardware. GPU's and modern CPU's implement Single Instruction, Multiple Data (SIMD) pipelines allowing multiple operations to be computed in parallel.

In [ ]:
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

# Matrices


Matrices, are two dimensional arrays. The elements of a matrix are all of the same type. In notation, matrices are denoted with capitol, bold letter such as $\mathbf{X}$. In this and other labs, `m` is often the number of rows and `n` the number of columns. The elements of a matrix can be referenced with a two dimensional index. In math settings, numbers in the index typically run from 1 to n. In computer science and these labs, indexing will run from 0 to n-1.  

Code:
$$
X =
\begin{pmatrix} 
X_{00} & X_{01} & ... & X_{0 (n-1)} \\
X_{10} & X_{11} & ... & X_{1 (n-1)} \\
...    & ...    & ... & ...         \\
X_{(m-1)0} & X_{(m-1)1} & ... & X_{(m-1) (n-1)} \\
\end{pmatrix}
$$


Notation in math class
$$
X =
\begin{pmatrix} 
X_{11} & X_{12} & ... & X_{1n} \\
X_{21} & X_{22} & ... & X_{1n} \\
...    & ...    & ... & ...    \\
X_{m1} & X_{m2} & ... & X_{mn} \\
\end{pmatrix}
$$




## NumPy Arrays

NumPy's basic data structure is an indexable, n-dimensional *array* containing elements of the same type (`dtype`). These were described earlier. Matrices have a two-dimensional (2-D) index [m,n].

In Course 1, 2-D matrices are used to hold training data. Training data is $m$ examples by $n$ features creating an (m,n) array. Course 1 does not do operations directly on matrices but typically extracts an example as a vector and operates on that. Below you will review: 
- data creation
- slicing and indexing

## Matrix Creation
The same functions that created 1-D vectors will create 2-D or n-D arrays. Here are some examples


Below, the shape tuple is provided to achieve a 2-D result. Notice how NumPy uses brackets to denote each dimension. Notice further than NumPy, when printing, will print one row per line.


In [69]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}")
print(f"a = {a}\n")                     


a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}")
print(f"a = \n{a}\n") 


a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}")
print(f"a = {a}") 

a shape = (1, 5)
a = [[0. 0. 0. 0. 0.]]

a shape = (2, 1)
a = 
[[0.]
 [0.]]

a shape = (1, 1)
a = [[0.95152619]]


One can also manually specify data. Dimensions are specified with additional brackets matching the format in the printing above.

In [96]:
a = np.array([[5], [4], [3]])
print(f"a shape = {a.shape}")
print(f"np.array: a = \n{a} \n")


# You can also continueon the next line for better readability
a = np.array([[5],   
              [4],   
              [3]])
print(f"a shape = {a.shape}")
print(f"np.array: a = \n{a}")

a shape = (3, 1)
np.array: a = 
[[5]
 [4]
 [3]] 

a shape = (3, 1)
np.array: a = 
[[5]
 [4]
 [3]]


## Operations on Matrices
Let's explore some operations using matrices.

### Indexing


Matrices include a second index. The two indexes describe [row, column]. Access can either return an element or a row/column. See below:

In [84]:
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}")
print(f"a= \n{a}\n")

print("Access an element in the matrix:")
print(f"a[2,0].shape: {a[2, 0].shape}")
print(f"a[2,0] = {a[2, 0]}")
print(f"type(a[2,0]) = {type(a[2, 0])}\nAccessing an element returns a scalar\n")

print("Access a row in the matrix:")
print(f"a[2].shape: {a[2].shape}")
print(f"a[2] = {a[2]}")
print(f"type(a[2]): = {type(a[2])}")

a.shape: (3, 2)
a= 
[[0 1]
 [2 3]
 [4 5]]

Access an element in the matrix:
a[2,0].shape: ()
a[2,0] = 4
type(a[2,0]) = <class 'numpy.int64'>
Accessing an element returns a scalar

Access a row in the matrix:
a[2].shape: (2,)
a[2] = [4 5]
type(a[2]): = <class 'numpy.ndarray'>


It is worth drawing attention to the last example. Accessing a matrix by just specifying the row will return a *1-D vector*.

**Reshape**  
The previous example used [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) to shape the array.  
`a = np.arange(6).reshape(-1, 2) `   
This line of code first created a *1-D Vector* of six elements. It then reshaped that vector into a *2-D* array using the reshape command. This could have been written:  
`a = np.arange(6).reshape(3, 2) `  
To arrive at the same 3 row, 2 column array.
The -1 argument tells the routine to compute the number of rows given the size of the array and the number of columns.


### Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

In [99]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("\na[0, 2:7:1] = ", a[0, 2:7:1])
print("a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array \n")

#access 5 consecutive elements (start:stop:step) in two rows
print("\na[:, 2:7:1] = \n", a[:, 2:7:1])
print("a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array \n")

# access all elements
print("a[:,:] = \n", a[:,:])
print("a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("\na[1,:] = ", a[1,:])
print("a[1,:].shape =", a[1,:].shape, "a 1-D array")

# same as
print("\na[1]   = ", a[1])
print("a[1].shape   =", a[1].shape, "a 1-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

a[0, 2:7:1] =  [2 3 4 5 6]
a[0, 2:7:1].shape = (5,) a 1-D array 


a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]]
a[:, 2:7:1].shape = (2, 5) a 2-D array 

a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[:,:].shape = (2, 10)

a[1,:] =  [10 11 12 13 14 15 16 17 18 19]
a[1,:].shape = (10,) a 1-D array

a[1]   =  [10 11 12 13 14 15 16 17 18 19]
a[1].shape   = (10,) a 1-D array


# Task: Mean Squared Error
Now, let's practice your skills that you just have learned in this notebook. Implement following mean squared error

$$
L(\vec{a}, \vec{b}) = \frac{1}{n} \sum^{n-1}_{i=0} (a_i - b_i)^2
$$

for two vectors in two ways
 
- Loop Implementation
- Vectorized Implementation

In [48]:
def mean_squared_error_loop(a, b):
    """
    Loop implementation of a mean squared error between two vectors
    Arguments:
      a: numpy nd-array with size (n)
      b: numpy nd-array with size (n)
    Returns:
      error: scalar which is the squared error of a and b
    """
    error = 0    
    n = len(a)
    ### START CODE HERE ###
    
    for i in range(n):
        error += (a[i]-b[i])**2
    error /= n
    
    ### END CODE HERE ###
    return error

In [49]:
np.random.seed(1337)
a = np.random.randn(1000)
b = np.random.randn(1000)
mean_squared_error_loop(a, b)

1.8469650817618783

### Expected Result
1.8469650817618783

In [50]:
def mean_squared_error_vectorized(a, b):
    """
    Vectorized implementation of a squared error between two vectors
    Arguments:
      a: numpy nd-array with size (n)
      b: numpy nd-array with size (n)
    Returns:
      error: scalar which is the squared error of a and b
    """
    error = 0    
    ### START CODE HERE ###
    
    error = (1/len(a)) * np.sum((a-b)**2)
    
    ### END CODE HERE ###
    return error

In [51]:
np.random.seed(1337)
a = np.random.randn(1000)
b = np.random.randn(1000)
mean_squared_error_vectorized(a, b)

1.846965081761879

### Expected Result
1.846965081761879

## Time Comparison

In [52]:
tic = time.time()
mean_squared_error_loop(a, b)
toc = time.time()
print(f"Loop version duration: {1000*(toc-tic):.4f} ms ")


tic = time.time()
mean_squared_error_vectorized(a, b)
toc = time.time()
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

loop version duration: 1.1654 ms 
vectorized version duration: 0.0961 ms 


# Wrap up

- You learned how to create Numpy arrays and matrices that are filled with random numbers or zeros
- You learned apply basic operations to Numpy arrays
- You learned the difference between slicing and indexing
- You learned that a vectorized implementation is often much faster than loop-based solutions